WebApp/Controllers/InicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Datos;
using WebApp.Models;
using WebApp.Servicios;

namespace WebApp.Controllers
{
    //Modelo clase del login
    public class InicioController : Controller
    {
        // GET: Inicio
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string correo, string clave)
        {
            UsuarioDTO usuario = DBUsuario.Validar(correo, UtilidadServicio.ConvertirSHA256(clave));

            if (usuario != null)
            {
                if (!usuario.Confirmado)
                {
                    ViewBag.Mensaje = $"Falta confirmar su cuenta. Se le envio un correo a {correo}";
                }
                else if (usuario.Restablecer)
                {
                    ViewBag.Mensaje = $"Se ha solicitado restablecer su cuenta, favor revise su bandeja del correo {correo}";
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }

            }
            else
            {
                ViewBag.Mensaje = "No se encontraron coincidencias";
            }


            return View();
        }

        public ActionResult Registrar()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Registrar(UsuarioDTO usuario)
        {
            if (usuario.Clave != usuario.ConfirmarClave)
            {
                ViewBag.Nombre = usuario.Nombre;
                ViewBag.Correo = usuario.Correo;
                ViewBag.Mensaje = "Las contraseñas no coinciden";
                return View();
            }

            if (DBUsuario.Obtener(usuario.Correo) == null)
            {
                usuario.Clave = UtilidadServicio.ConvertirSHA256(usuario.Clave);
                usuario.Token = UtilidadServicio.GenerarToken();
                usuario.Restablecer = false;
                usuario.Confirmado = false;
                bool respuesta = DBUsuario.Registrar(usuario);

                if (respuesta)
                {
                    string path = HttpContext.Server.MapPath("~/Plantilla/Confirmar.html");
                    string content = System.IO.File.ReadAllText(path);
                    string url = string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Headers["host"], "/Inicio/Confirmar?token=" + usuario.Token);

                    string htmlBody = string.Format(content, usuario.Nombre, url);

                    CorreoDTO correoDTO = new CorreoDTO()
                    {
                        Para = usuario.Correo,
                        Asunto = "Correo confirmacion",
                        Contenido = htmlBody
                    };

                    bool enviado = CorreoServicio.Enviar(correoDTO);
                    ViewBag.Creado = true;
                    ViewBag.Mensaje = $"Su cuenta ha sido creada. Hemos enviado un mensaje al correo {usuario.Correo} para confirmar su cuenta";
                }
                else
                {
                    ViewBag.Mensaje = "No se pudo crear su cuenta";
                }



            }
            else
            {
                ViewBag.Mensaje = "El correo ya se encuentra registrado";
            }


            return View();
        }

        public ActionResult Confirmar(string token)
        {
            ViewBag.Respuesta = DBUsuario.Confirmar(token);
            return View();
        }

        public ActionResult Restablecer()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Restablecer(string correo)
        {
            UsuarioDTO usuario = DBUsuario.Obtener(correo);
            ViewBag.Correo = correo;
            if (usuario != null)
            {
                bool respuesta = DBUsuario.RestablecerActualizar(1, usuario.Clave, usuario.Token);

                if (respuesta)
                {
                    string path = HttpContext.Server.MapPath("~/Plantilla/Restablecer.html");
                    string content = System.IO.File.ReadAllText(path);
                    string url = string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Headers["host"], "/Inicio/Actualizar?token=" + usuario.Token);

                    string htmlBody = string.Format(content, usuario.Nombre, url);

                    CorreoDTO correoDTO = new CorreoDTO()
                    {
                        Para = correo,
                        Asunto = "Restablecer cuenta",
                        Contenido = htmlBody
                    };

                    bool enviado = CorreoServicio.Enviar(correoDTO);
                    ViewBag.Restablecido = true;
                }
                else
                {
                    ViewBag.Mensaje = "No se pudo restablecer la cuenta";
                }

            }
            else
            {
                ViewBag.Mensaje = "No se encontraron coincidencias con el correo";
            }

            return View();
        }

        public ActionResult Actualizar(string token)
        {
            ViewBag.Token = token;
            return View();
        }

        [HttpPost]
        public ActionResult Actualizar(string token, string clave, string confirmarClave)
        {
            ViewBag.Token = token;
            if (clave != confirmarClave)
            {
                ViewBag.Mensaje = "Las contraseñas no coinciden";
                return View();
            }

            bool respuesta = DBUsuario.RestablecerActualizar(0, UtilidadServicio.ConvertirSHA256(clave), token);

            if (respuesta)
                ViewBag.Restablecido = true;
            else
                ViewBag.Mensaje = "No se pudo actualizar";

            return View();
        }
    }

}

WebApp/Views/Inicio/Actualizar.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Actualizar</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="row justify-content-center mt-5">

        <div class="col-5">

            <div class="card">
                <div class="card-header"><h3 class="text-center">Restablecer Contraseña</h3></div>
                <div class="card-body">
                    @if (ViewBag.Restablecido == null)
                    {
                        <form action="@Url.Action("Actualizar","Inicio")" method="post">
                            <input type="hidden" name="token" value="@ViewBag.Token" />

                            <div class="mb-3">
                                <label>Ingresar una nueva contraseña</label>
                                <input type="password" class="form-control" name="clave" required />
                            </div>
                            <div class="mb-3">
                                <label>Confirmar contraseña</label>
                                <input type="password" class="form-control" name="confirmarClave" required />
                            </div>

                            @if (ViewBag.Mensaje != null)
                            {
                                <div class="alert alert-danger">
                                    @ViewBag.Mensaje
                                </div>
                            }

                            <div class="mb-3">
                                <div class="d-grid">
                                    <button class="btn btn-primary" type="submit">Combiar contraseña</button>
                                </div>
                            </div>


                        </form>
                    }
                    else
                    {
                        <div class="alert alert-success">
                            <p>Su contraseña fue restablecida, ahora puede ingresar a su cuenta con su nueva clave.</p>
                            <a class="btn btn-success" href="@Url.Action("Login","Inicio")">Ingresar</a>
                        </div>
                    }
                </div>
            </div>

        </div>

    </div>
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

WebApp/Views/Inicio/Confirmar.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Confirmar</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="container mt-3">
        @if ((bool)ViewBag.Respuesta)
        {
            <div class="alert alert-success">
                <p><b>Listo!</b>&nbsp; Su cuenta fue confirmada. Ahora puede acceder</p>
                <a class="btn btn-success" href="@Url.Action("Login","Inicio")">Ingresar</a>
            </div>
        }
        else
        {
            <div class="alert alert-danger">
                <p>No se pudo confirmar el correo</p>
            </div>
        }
    </div>
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

WebApp/Views/Inicio/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="row justify-content-center mt-5">

        <div class="col-5">

            <div class="card">
                <div class="card-header"><h3 class="text-center">Login</h3></div>
                <div class="card-body">

                   <form action="@Url.Action("Login","Inicio")" method="post">

                        <div class="mb-3">
                            <label>Correo</label>
                            <input type="email" class="form-control" name="correo" required />
                        </div>
                        <div class="mb-3">
                            <label>Contraseña</label>
                            <input type="password" class="form-control" name="clave" required />
                        </div>

                        @if (ViewBag.Mensaje != null)
                        {
                            <div class="alert alert-danger">
                                @ViewBag.Mensaje
                            </div>
                        }

                        <div class="mb-3">
                            <div class="d-grid">
                                <button class="btn btn-primary" type="submit">Ingresar </button>
                                <a class="btn btn-link" href="@Url.Action("Registrar","Inicio")">No tienes una cuenta? Registrate!</a>
                                <a class="btn btn-link" href="@Url.Action("Restablecer","Inicio")">Has olvidado tu contraseña?</a>
                            </div>
                        </div>
                    </form>

                </div>
            </div>

        </div>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

WebApp/Views/Inicio/Registrar.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Registrar</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="row justify-content-center mt-5">

        <div class="col-5">

            <div class="card">
                <div class="card-header"><h3 class="text-center">Registrar cuenta</h3></div>
                <div class="card-body">

                    @if (ViewBag.Creado == null)
                    {
                        <form action="@Url.Action("Registrar","Inicio")" method="post">

                            <div class="mb-3">
                                <label>Nombre</label>
                                <input type="text" class="form-control" name="Nombre" value="@(ViewBag.Nombre !=null ? ViewBag.Nombre : "")" required />
                            </div>
                            <div class="mb-3">
                                <label>Correo</label>
                                <input type="email" class="form-control" name="Correo" value="@(ViewBag.Correo !=null ? ViewBag.Correo : "")" required />
                            </div>
                            <div class="mb-3">
                                <label>Contraseña</label>
                                <input type="password" class="form-control" name="Clave" required />
                            </div>
                            <div class="mb-3">
                                <label>Confirmar Contraseña</label>
                                <input type="password" class="form-control" name="ConfirmarClave" required />
                            </div>

                            @if (ViewBag.Mensaje != null)
                            {
                                <div class="alert alert-danger">
                                    @ViewBag.Mensaje
                                </div>
                            }

                            <div class="mb-3">
                                <div class="d-grid">
                                    <button class="btn btn-primary" type="submit">Registrarse </button>
                                    <a class="btn btn-link" href="@Url.Action("Login","Inicio")">Ya tienes una cuenta? Inicia sesion</a>
                                </div>
                            </div>


                        </form>
                    }
                    else
                    {
                        <div class="alert alert-success">
                            <p>@ViewBag.Mensaje</p>
                            <a class="btn btn-success" href="@Url.Action("Login","Inicio")">Ingresar</a>
                        </div>
                    }


                </div>
            </div>

        </div>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

WebApp/Views/Inicio/Restablecer.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Restablecer</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="row justify-content-center mt-5">

        <div class="col-5">

            <div class="card">
                <div class="card-header"><h3 class="text-center">Restablecer cuenta</h3></div>
                <div class="card-body">
                    @if (ViewBag.Restablecido == null)
                    {
                        <form action="@Url.Action("Restablecer","Inicio")" method="post">
                            <p>Ingrese su dirección de correo electrónico y le enviaremos un enlace para restablecer su contraseña.</p>

                            <div class="mb-3">
                                <label>Correo</label>
                                <input type="email" class="form-control" name="correo" value="@(ViewBag.Correo !=null ? ViewBag.Correo : "")" required />
                            </div>

                            @if (ViewBag.Mensaje != null)
                            {
                                <div class="alert alert-danger">
                                    @ViewBag.Mensaje
                                </div>
                            }

                            <div class="mb-3">
                                <div class="d-grid">
                                    <button class="btn btn-primary" type="submit">Restablecer</button>
                                    <a class="btn btn-link" href="@Url.Action("Login","Inicio")">Volver</a>
                                </div>
                            </div>


                        </form>
                    }
                    else
                    {
                        <div class="alert alert-success">
                            <p>Su contraseña fue restablecida, le enviamos un mensaje su correo para restablecer.</p>
                            <a class="btn btn-success" href="@Url.Action("Login","Inicio")">Ingresar</a>
                        </div>
                    }

                </div>
            </div>

        </div>

    </div>
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>